# <LEFT>Data Cleaning

In [8]:
import pandas as pd
import numpy as np

In [10]:
data = pd.read_csv(r"D:/Tableau/Project/website_sessions.csv")

In [12]:
session = data.copy()

In [14]:
session.head(15)

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
5,6,2012-03-19 09:05:46,6,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
6,7,2012-03-19 09:06:27,7,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
7,8,2012-03-19 09:17:17,8,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
8,9,2012-03-19 09:27:56,9,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
9,10,2012-03-19 09:35:37,10,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
10,11,2012-03-19 09:37:42,11,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
11,12,2012-03-19 09:39:57,12,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
12,13,2012-03-19 09:45:29,13,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
13,14,2012-03-19 09:45:47,14,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
14,15,2012-03-19 09:57:14,15,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com

In [16]:
session.tail()

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
472866,472867,2015-03-19 07:49:25,394314,0,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:36,394315,0,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:40,394316,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:29,394317,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,NaN,NaN,NaN,mobile,NaN

In [18]:
session['utm_source'].mode()

0    gsearch
Name: utm_source, dtype: object

In [20]:
session['utm_campaign'].mode()

0    nonbrand
Name: utm_campaign, dtype: object

In [107]:
session['utm_content'].mode()

0    g_ad_1
Name: utm_content, dtype: object

In [109]:
session['http_referer'].mode()

0    https://www.gsearch.com
Name: http_referer, dtype: object

In [111]:
session['http_referer'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
472866    False
472867    False
472868    False
472869    False
472870     True
Name: http_referer, Length: 472871, dtype: bool

In [113]:
session[session['utm_source'].isna()]

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
904,905,2012-03-25 07:24:18,905,0,NaN,NaN,NaN,mobile,NaN
914,915,2012-03-25 10:45:03,915,0,NaN,NaN,NaN,mobile,NaN
933,934,2012-03-25 14:23:48,934,0,NaN,NaN,NaN,desktop,NaN
1044,1045,2012-03-26 11:54:49,846,1,NaN,NaN,NaN,desktop,NaN
1050,1051,2012-03-26 12:48:41,152,1,NaN,NaN,NaN,desktop,NaN
...,...,...,...,...,...,...,...,...,...
472835,472836,2015-03-19 06:25:38,394289,0,NaN,NaN,NaN,desktop,https://www.gsearch.com
472846,472847,2015-03-19 06:57:13,378178,1,NaN,NaN,NaN,mobile,https://www.gsearch.com
472860,472861,2015-03-19 07:38:28,383375,1,NaN,NaN,NaN,desktop,NaN
472863,472864,2015-03-19 07:41:11,394311,0,NaN,NaN,NaN,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,NaN,NaN,NaN,mobile,NaN

In [115]:
session.fillna(method='ffill', inplace = True)

C:\Users\sayan mukherjee\AppData\Local\Temp\ipykernel_21352\3290390210.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  session.fillna(method='ffill', inplace = True)

In [117]:
session

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472866,472867,2015-03-19 07:49:25,394314,0,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:36,394315,0,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:40,394316,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:29,394317,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

In [119]:
session.to_csv("D:/Tableau/Project/website_session_clean.csv", index=False)

In [121]:
order = pd.read_csv(r"D:/Tableau/Project/Maven+Fuzzy+Factory/orders.csv")

In [123]:
order

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49
...,...,...,...,...,...,...,...,...
32308,32309,2015-03-19 03:58:12,472795,394255,1,1,49.99,19.49
32309,32310,2015-03-19 04:10:43,472798,394257,4,1,29.99,9.49
32310,32311,2015-03-19 05:27:28,472809,394268,2,2,89.98,31.98
32311,32312,2015-03-19 05:35:57,472814,394273,4,1,29.99,9.49
32312,32313,2015-03-19 05:38:31,472818,386000,1,1,49.99,19.49

In [125]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ MB

In [127]:
order.describe()

,order_id,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
count,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000
mean,16157.000000,258292.288707,215691.622629,1.392474,1.238666,59.991636,22.355406
std,9328.103961,132427.649842,108402.203189,0.732277,0.426274,17.808771,6.238621
min,1.000000,20.000000,13.000000,1.000000,1.000000,29.990000,9.490000
25%,8079.000000,144828.000000,124135.000000,1.000000,1.000000,49.990000,19.490000
50%,16157.000000,263554.000000,221461.000000,1.000000,1.000000,49.990000,19.490000
75%,24235.000000,374799.000000,310542.000000,2.000000,1.000000,59.990000,22.490000
max,32313.000000,472818.000000,394273.000000,4.000000,2.000000,109.980000,41.980000

In [129]:
order_item_refund = pd.read_csv(r"D:/Tableau/Project/Maven+Fuzzy+Factory/order_item_refunds.csv")

In [131]:
order_item_refund

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99
...,...,...,...,...,...
1726,1727,2015-03-30 09:37:23,39950,32255,59.99
1727,1728,2015-03-30 21:33:51,39671,32049,49.99
1728,1729,2015-03-31 19:59:48,39729,32090,49.99
1729,1730,2015-04-01 03:54:48,39717,32079,59.99
1730,1731,2015-04-01 18:11:08,39947,32252,45.99

In [133]:
order_item_refund.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   object
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: float64(1), int64(3), object(1)
memory usage: 67.7+ KB

In [135]:
order_item_refund.describe()

       order_item_refund_id  order_item_id      order_id  refund_amount_usd
count           1731.000000    1731.000000   1731.000000        1731.000000
mean             866.000000   18472.214905  15868.242057          49.300225
std              499.840975   11438.074606   9096.061945           4.956015
min                1.000000      57.000000     57.000000          29.990000
25%              433.500000    7417.000000   7412.000000          49.990000
50%              866.000000   19858.000000  17375.000000          49.990000
75%             1298.500000   26900.000000  22539.500000          49.990000
max             1731.000000   39950.000000  32255.000000          59.990000

In [137]:
order_item = pd.read_csv(r"D:/Tableau/Project/Maven+Fuzzy+Factory/order_items.csv")

In [139]:
order_item

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49
...,...,...,...,...,...,...,...
40020,40021,2015-03-19 04:10:43,32310,4,1,29.99,9.49
40021,40022,2015-03-19 05:27:28,32311,2,1,59.99,22.49
40022,40023,2015-03-19 05:27:28,32311,4,0,29.99,9.49
40023,40024,2015-03-19 05:35:57,32312,4,1,29.99,9.49
40024,40025,2015-03-19 05:38:31,32313,1,1,49.99,19.49

In [141]:
order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  object
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: float64(2), int64(4), object(1)
memory usage: 2.1+ MB

In [143]:
order_item.describe()

,order_item_id,order_id,product_id,is_primary_item,price_usd,cogs_usd
count,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000
mean,20013.000000,17121.957502,1.770019,0.807320,48.432473,18.047976
std,11554.366599,9053.765867,1.085561,0.394408,8.012370,3.856821
min,1.000000,1.000000,1.000000,0.000000,29.990000,9.490000
25%,10007.000000,9871.000000,1.000000,1.000000,49.990000,19.490000
50%,20013.000000,17490.000000,1.000000,1.000000,49.990000,19.490000
75%,30019.000000,24818.000000,2.000000,1.000000,49.990000,19.490000
max,40025.000000,32313.000000,4.000000,1.000000,59.990000,22.490000

In [145]:
order = pd.read_csv(r"D:/Tableau/Project/Maven+Fuzzy+Factory/orders.csv")

In [147]:
order

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49
...,...,...,...,...,...,...,...,...
32308,32309,2015-03-19 03:58:12,472795,394255,1,1,49.99,19.49
32309,32310,2015-03-19 04:10:43,472798,394257,4,1,29.99,9.49
32310,32311,2015-03-19 05:27:28,472809,394268,2,2,89.98,31.98
32311,32312,2015-03-19 05:35:57,472814,394273,4,1,29.99,9.49
32312,32313,2015-03-19 05:38:31,472818,386000,1,1,49.99,19.49

In [149]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ MB

In [151]:
order.describe()

,order_id,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
count,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000
mean,16157.000000,258292.288707,215691.622629,1.392474,1.238666,59.991636,22.355406
std,9328.103961,132427.649842,108402.203189,0.732277,0.426274,17.808771,6.238621
min,1.000000,20.000000,13.000000,1.000000,1.000000,29.990000,9.490000
25%,8079.000000,144828.000000,124135.000000,1.000000,1.000000,49.990000,19.490000
50%,16157.000000,263554.000000,221461.000000,1.000000,1.000000,49.990000,19.490000
75%,24235.000000,374799.000000,310542.000000,2.000000,1.000000,59.990000,22.490000
max,32313.000000,472818.000000,394273.000000,4.000000,2.000000,109.980000,41.980000

In [153]:
product = pd.read_csv(r"D:/Tableau/Project/Maven+Fuzzy+Factory/products.csv")

In [155]:
product

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

In [157]:
website_pageview = pd.read_csv(r"D:/Tableau/Project/Maven+Fuzzy+Factory/website_pageviews.csv")

In [159]:
website_pageview

,website_pageview_id,created_at,website_session_id,pageview_url
0,1,2012-03-19 08:04:16,1,/home
1,2,2012-03-19 08:16:49,2,/home
2,3,2012-03-19 08:26:55,3,/home
3,4,2012-03-19 08:37:33,4,/home
4,5,2012-03-19 09:00:55,5,/home
...,...,...,...,...
1188119,1188120,2015-03-19 07:57:32,472866,/shipping
1188120,1188121,2015-03-19 07:58:13,472870,/the-original-mr-fuzzy
1188121,1188122,2015-03-19 07:59:07,472866,/billing-2
1188122,1188123,2015-03-19 07:59:08,472871,/home
1188123,1188124,2015-03-19 07:59:32,472868,/the-original-mr-fuzzy

In [161]:
website_pageview.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188124 entries, 0 to 1188123
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1188124 non-null  int64
 1   created_at           1188124 non-null  object
 2   website_session_id   1188124 non-null  int64
 3   pageview_url         1188124 non-null  object
dtypes: int64(2), object(2)
memory usage: 36.3+ MB

In [163]:
website_session = pd.read_csv(r"D:/Tableau/Project/Maven+Fuzzy+Factory/website_session_clean.csv")

In [165]:
website_session

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472866,472867,2015-03-19 07:49:25,394314,0,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:36,394315,0,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:40,394316,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:29,394317,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

In [167]:
website_session.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  object
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          472871 non-null  object
 5   utm_campaign        472871 non-null  object
 6   utm_content         472871 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        472871 non-null  object
dtypes: int64(3), object(6)
memory usage: 32.5+ MB

In [169]:
website_session.describe()

       website_session_id        user_id  is_repeat_session
count       472871.000000  472871.000000      472871.000000
mean        236436.000000  198037.970163           0.166119
std         136506.243908  111992.997798           0.372188
min              1.000000       1.000000           0.000000
25%         118218.500000  101966.500000           0.000000
50%         236436.000000  199483.000000           0.000000
75%         354653.500000  294433.000000           0.000000
max         472871.000000  394318.000000           1.000000

In [171]:
website_session

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472866,472867,2015-03-19 07:49:25,394314,0,gsearch,brand,g_ad_2,desktop,https://www.gsearch.com
472867,472868,2015-03-19 07:54:36,394315,0,bsearch,nonbrand,b_ad_1,mobile,https://www.bsearch.com
472868,472869,2015-03-19 07:55:40,394316,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
472869,472870,2015-03-19 07:56:29,394317,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
472870,472871,2015-03-19 07:59:08,394318,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

In [173]:
order

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49
...,...,...,...,...,...,...,...,...
32308,32309,2015-03-19 03:58:12,472795,394255,1,1,49.99,19.49
32309,32310,2015-03-19 04:10:43,472798,394257,4,1,29.99,9.49
32310,32311,2015-03-19 05:27:28,472809,394268,2,2,89.98,31.98
32311,32312,2015-03-19 05:35:57,472814,394273,4,1,29.99,9.49
32312,32313,2015-03-19 05:38:31,472818,386000,1,1,49.99,19.49